### ISSUE TITLE
Nueva versión no funciona

### ISSUE THREAD

**Issue by jesbrz** [sigdeletras/Spanish_Inspire_Catastral_Downloader#26]
Hola, he instalado la nueva versión 2.0 sobre Qgis 3.32.3 y el plugin no funciona. La ventana de diálogo se abre correctamente, permite elegir la provincia, el municipio, la carpeta de descarga y las diferentes opciones pero una vez le das a descargar datos del Catastro, se queda parado y no hace nada, la barra de progreso no avanza. Sé que son pocos datos para poder arreglar algo, pero no lanza ningún mensaje de error y en la consola de Python tampoco aparece nada.

La versión anterior funcionaba correctamente.

**Comment by sigdeletras** [comment]
Saludos

Esta nueva versión ha sido testeada tanto para 3.32.3 Lima como la la LTS 3.28.12 sin problemas. 
![image](https://github.com/sigdeletras/Spanish_Inspire_Catastral_Downloader/assets/4746157/8bfd94e0-5e1a-447a-be04-ded9d4b36a92)
Se ha incorporado un log de avisos accesible desde el Panel de Mensajes de Avisos (Pestaña SICD). Quizás desde aquí puedas obtener algo más información.
![image](https://github.com/sigdeletras/Spanish_Inspire_Catastral_Downloader/assets/4746157/9d42f8c5-ef91-49c0-b3b6-03c83dead384)

En el caso de querer usar la versión anterior (V1.1), puede ser descargada e instalada manualmente desde este repositorio en el apartado [Release](https://github.com/sigdeletras/Spanish_Inspire_Catastral_Downloader/releases/tag/V1.1)

**Comment by jesbrz** [comment]
Gracias por la respuesta. He mirado los mensajes, pero como puedes ver, no aporta ninguna información:

![Captura de Pantalla 2023-10-27 a las 19 34 34](https://github.com/sigdeletras/Spanish_Inspire_Catastral_Downloader/assets/19475313/a9d865f1-d2a1-4481-94b5-384f5e29be43)

(le he dado dos veces por si no lo había pillado a la primera)

Si encuentro el motivo del fallo te lo haré saber, si no volveré a la versión anterior, aunque me interesaba el no tener que convertir a geojson los GML.

**Comment by jesbrz** [comment]
Hola de nuevo. He desinstalado todos los complementos y he vuelto a instalar únicamente este en su nueva versión, pero no ha dado resultado y sigue sin funcionar, se queda pensando eternamente. Intentaré alguna cosa más a ver si al final lo consigo.

Ahora al intentar instalar la versión anterior me da este error y ya no me deja trabajar con ella:

```
`No se pudo cargar el complemento 'Spanish_Inspire_Catastral_Downloader-1.1' 

ModuleNotFoundError: No module named 'Spanish_Inspire_Catastral_Downloader-1' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'Spanish_Inspire_Catastral_Downloader-1'


Versión de Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versión de QGIS: 3.34.1-Prizren Prizren, 133927424d9 

Ruta de Python:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python`
```

Es solo para tu información y por si te sirve para algo en tus desarrollos. Un saludo y disculpa la molestia.

**Comment by jesbrz** [comment]
Sigo con mi empeño de poder usar el plugin. Tras actualizar a python 3.11.8 ya hemos avanzando algo, me da este mensaje de error. Eso sí, antes podía elegir provincia y municipio, ahora ya no me deja.
`2024-02-17T17:18:32     WARNING    Traceback (most recent call last):
              File "/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Spanish_Inspire_Catastral_Downloader/Spanish_Inspire_Catastral_Downloader.py", line 488, in rellenar_provincias
              response_json = json.loads(response)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/json/__init__.py", line 346, in loads
              return _default_decoder.decode(s)
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/json/decoder.py", line 337, in decode
              obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/json/decoder.py", line 355, in raw_decode
              raise JSONDecodeError("Expecting value", s, err.value) from None
             json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
             `

**Comment by rubengargar** [comment]
Por aquí estamos igual. Log:
```
2024-10-14T20:27:53     INFO    0. URL de Catastro https://www.catastro.hacienda.gob.es
2024-10-14T20:27:53     INFO    01.1 Obtenindo provincias (obtener_provincias)
2024-10-14T20:27:53     INFO    01.2 URL JSON Provincias de Catastro http://ovc.catastro.meh.es/OVCServWeb/OVCWcfCallejero/COVCCallejero.svc/json/ObtenerProvincias
2024-10-14T20:27:53     INFO    02. Rellenando provincias (rellenar_provincias)
2024-10-14T20:27:56     INFO    03.1 Obteniendo municipios (obtener_municipios) de la provincia 08 - BARCELONA
2024-10-14T20:27:56     INFO    03.2 URL JSON Municipios de Catastro de la 08 - BARCELONA: http://ovc.catastro.meh.es/OVCServWeb/OVCWcfCallejero/COVCCallejeroCodigos.svc/json/ObtenerMunicipiosCodigos?CodigoProvincia=08
2024-10-14T20:27:56     INFO    04. Rellenando municipios (rellenar_municipios)
2024-10-14T20:28:33     INFO    05 Inicio de descarga
2024-10-14T20:28:33     INFO    05.1 Genera variables zippath C:/Users/garci/OneDrive/Escritorio/sixnfive
2024-10-14T20:28:34     INFO    06.1 Genera url de descarga generate_download_url()
2024-10-14T20:28:34     INFO    06.1 Genera url de descarga generate_download_url()
2024-10-14T20:35:25     INFO    0. URL de Catastro https://www.catastro.hacienda.gob.es
2024-10-14T20:35:25     INFO    01.1 Obtenindo provincias (obtener_provincias)
2024-10-14T20:35:25     INFO    01.2 URL JSON Provincias de Catastro http://ovc.catastro.meh.es/OVCServWeb/OVCWcfCallejero/COVCCallejero.svc/json/ObtenerProvincias
2024-10-14T20:35:25     INFO    02. Rellenando provincias (rellenar_provincias)
2024-10-14T20:35:49     INFO    03.1 Obteniendo municipios (obtener_municipios) de la provincia 08 - BARCELONA
2024-10-14T20:35:49     INFO    03.2 URL JSON Municipios de Catastro de la 08 - BARCELONA: http://ovc.catastro.meh.es/OVCServWeb/OVCWcfCallejero/COVCCallejeroCodigos.svc/json/ObtenerMunicipiosCodigos?CodigoProvincia=08
2024-10-14T20:35:49     INFO    04. Rellenando municipios (rellenar_municipios)
2024-10-14T20:36:11     INFO    05 Inicio de descarga
2024-10-14T20:36:11     INFO    05.1 Genera variables zippath C:/Users/garci/OneDrive/Escritorio/sixnfive
2024-10-14T20:36:11     INFO    06.1 Genera url de descarga generate_download_url()
2024-10-14T20:36:11     INFO    06.1 Genera url de descarga generate_download_url()
```

**Comment by sigdeletras** [comment]
@rubengargar Veo que ya estás usando la última versió 2.1. En el log, no detecto ningún error.  

El paso siguiente es la selección de un municipio de la provincia de Barcelona y realizar la descarga en la carpeta indicada.
Si posteriormente quieres que se añada en QGIS, haz clic en "Añadir capas al proyecto de QGIS"

![image](https://github.com/user-attachments/assets/963ef24e-7547-491b-866b-e1ef9efd6383)

**Comment by rubengargar** [comment]
@sigdeletras Uso el plugin desde hace tiempo ya que es fantástico, pero recientemente tengo ese mismo problema tanto en Mac como en Windows,

Añado una imagen a parte del log, pero una vez pulso en Descargar datos de catastro se queda a 0% y no avanza ni aunque lo deje tiempo pensando.
<img width="426" alt="image" src="https://github.com/user-attachments/assets/b256072a-d301-4bb9-92fa-22594b8c79a9">
